# Generated by Django 5.0.1 on 2024-06-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_task_taskitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
